name: CI/CD Pipeline

on:
  push:  # Trigger on any branch push
    branches:
      - '*'  # All branches
  pull_request:
    branches: [ "master" ]

jobs:
  build:
  runs-on: ubuntu-latest

  steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Build and test
      run: npm run build && npm test
